# SPDX-License-Identifier: CC BY-NC-SA 4.0
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike
# 4.0 International License. Making code open source is essential for scientific
# transparency and reproducibility. Providing access to the code allows researchers to
# verify, replicate, and expand upon results, which supports scientific progress. Current
# top-tier conferences encourage opensource code for the purpose of reproducibility that
# is de-facto an established expectation of the research community. Opensource code as
# part of publication should not affect the performance of an invention both from a
# commercial and IP point of view.

# --- What this file is -----------------------------------------------------------------------
# Builds the two ReActNet rows by constructing the author's models from the pinned clone and
# tracing them. Holds the three things specific to that repository: how it is imported, how its
# non-standard convolution class is read, and which of its layers are binary.

"""ReActNet, through its own repository.

Both published ReActNet rows -- ``ReactNet-BiReal18`` and ``ReactNetA`` -- are regenerated by
constructing the author's model from ``energy_ECML/SOTA/repos/reactnet`` and tracing it, rather than
by recovering ``data/profile_reactnet.pickle`` (the notebook that produced it is not expected to
be findable).  The clone is pinned in ``energy_ECML/SOTA/sources.toml``.

**What is method-specific here, and what is not.**  Three things live in this module and nowhere
else: how the repository's model is imported, how its convolution class is read (the repository
does not use ``nn.Conv2d`` -- see :func:`describe`), and which layers are binary
(:func:`K_policy`).  The geometry comes from the trace and the pricing from the shared model.

**Bit widths.**  The 8-bit storage assumption
(``energy_ECML/SOTA/README.md``, and the ``$^\\dagger$`` on both published rows): a binary
convolution takes binary *operands* but its feature maps are *stored* at 8 bits, because the
real-valued skip path of a Bi-Real style network means the tensors are not binary in memory;
first and last layers are not quantized, so 8 bits per weight; the network input is 8 bits.

**Skip connections cost nothing extra here**, under
:attr:`~TNet.energy_ECML.spec.Assumptions.skip_read_when_not_already_an_input`.
Every residual in both models is added to the output of a convolution whose *own input* is the
tensor being added -- ``out = binary_conv(sign(x + bias)) + x`` -- so the tensor is read once and
the addition is fused.  This is the case the appendix names explicitly: *"In BiReal architecture
(used in ReactNet-BiReal), the skip connection is around one convolution block only and thus can
be fused with the convolution, so we do not add extra memory accesses for it."*

ReActNet-A adds two shapes of that same pattern, neither of which is a skip over two
convolutions:

* a *reduction* block adds ``avg_pool(x)`` rather than ``x``.  The pooled tensor is a reduction
  of the convolution's own input, computed inline from the values already read, so it is charged
  as the appendix charges a fused pooling: nothing extra.
* a *channel-doubling* block runs two 1x1 convolutions on the same binarized tensor, adds the
  block's input to each, and concatenates.  The addend is again an input of the convolution that
  consumes it; the concatenation is free.  The two convolutions do each read
  their common input, which is what ``memory_traffic="one_pass"`` counts.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from typing import Optional

from ..adapters.traced import ConvLike, describe_native, repo_dir, specs_from_trace, trace

__all__ = ["load_module", "reactnet_a_model", "birealnet18_model", "describe", "K_policy",
           "reactnet_a", "reactnet_bireal18"]

#: Files of the clone that define the two models.  ``2_step2`` is the stage with both weights and
#: activations binarized, which is what the published accuracies (69.4 / 65.5) are.
_A_PATH = ("mobilenet", "2_step2", "reactnet.py")
_BIREAL_PATH = ("resnet", "2_step2", "birealnet.py")


def load_module(*relpath: str):
    """Import one file of the clone as a module, without putting the repo on ``sys.path``.

    The two model files are not a package and share module names with each other (both define
    ``BasicBlock``, ``HardBinaryConv``); loading each by its full path under a unique name keeps
    them independent.
    """
    path = os.path.join(repo_dir("reactnet"), *relpath)
    name = "tnet_reactnet_repo_" + "_".join(relpath).replace(".py", "").replace(os.sep, "_")
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def reactnet_a_model():
    """ReActNet-A: the MobileNet-geometry model of ``mobilenet/2_step2/reactnet.py``."""
    return load_module(*_A_PATH).reactnet(num_classes=1000)


def birealnet18_model():
    """ReActNet-BiReal18: the ResNet-18-geometry model of ``resnet/2_step2/birealnet.py``."""
    return load_module(*_BIREAL_PATH).birealnet18()


def _binary_conv_types() -> tuple:
    """The repository's own convolution class, from both model files.

    Each file defines its own ``HardBinaryConv``; they are two distinct classes with identical
    bodies, so an ``isinstance`` check has to know both.
    """
    types = []
    for relpath in (_A_PATH, _BIREAL_PATH):
        try:
            types.append(load_module(*relpath).HardBinaryConv)
        except FileNotFoundError:                  # the clone is not there; nothing to describe
            pass
    return tuple(types)


def describe(module) -> Optional[ConvLike]:
    """Geometry of a ``HardBinaryConv``, which is not an ``nn.Conv2d``.

    The class keeps its weights as a flat ``nn.Parameter`` of shape ``(C_out C_in k k, 1)`` and
    calls ``F.conv2d`` itself, so it has no ``.weight`` of the right shape, no ``.groups`` and no
    ``.dilation``.  What it does have is ``.shape`` -- the ``(C_out, C_in, k, k)`` it reshapes to
    -- and ``.stride``.  It is never grouped and never dilated.
    """
    binary = _binary_conv_types()
    if binary and isinstance(module, binary):
        return ConvLike(
            weight_shape=tuple(int(v) for v in module.shape),
            stride=int(module.stride),
            dilation=1,
            groups=1,
        )
    return describe_native(module)


def K_policy(K_stored: int = 256, K_first_last: int = 256, K_in_first: int = 256):
    """A layer is binary exactly when it is one of the repository's ``HardBinaryConv``.

    Every argument and every value returned is a number of **states**: a binary layer is ``2``,
    the 8-bit cap is ``256``.  See the naming convention in :mod:`TNet.energy_ECML.spec`.

    Stating it by module type rather than by position is what makes it checkable: the layers the
    paper calls binary are precisely the ones the author's code implemented with the binary
    convolution class, and the real-valued stem, classifier and Bi-Real downsample convolutions
    are precisely the remaining ``nn.Conv2d``/``nn.Linear``.
    """
    binary = _binary_conv_types()

    def policy(index: int, name: str, module) -> dict:
        is_binary = bool(binary) and isinstance(module, binary)
        return dict(
            K_in_stored=K_in_first if index == 0 else K_stored,
            K_in_operand=K_in_first if index == 0 else (2 if is_binary else K_stored),
            K_W_stored=2 if is_binary else K_first_last,
            K_W_operand=2 if is_binary else K_first_last,
            K_out_stored=K_stored,
        )
    return policy


def _specs(model, **kw):
    ops = trace(model, extra_compute=_binary_conv_types())
    return specs_from_trace(ops, K_policy(**kw), describe=describe)


def reactnet_a(**kw):
    """``list[LayerSpec]`` for ReActNet-A."""
    return _specs(reactnet_a_model(), **kw)


def reactnet_bireal18(**kw):
    """``list[LayerSpec]`` for ReActNet-BiReal18, traced from the same repository."""
    return _specs(birealnet18_model(), **kw)
